[package]
name = "ferium"
version = "3.12.1"
edition = "2021"
authors = ["theRookieCoder <ileshkt@gmail.com>", "Daniel Hauck (SolidTux)"]
description = "Ferium is a CLI program for managing Minecraft mods from Modrinth, CurseForge, and Github Releases"
exclude = ["tests"] # Don't need tests for installing using crates.io
repository = "https://github.com/theRookieCoder/ferium"
categories = ["command-line-utilities"]
readme = "README.md"
license = "MPL-2.0"
keywords = [
	"minecraft",
	"cli",
	"mod-manager",
	"modrinth",
	"curseforge"
]

[features]
default = ["gui"]
gui = ["libium/gui"]

[dependencies]
# Use `rustls` rather than OpenSSL
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0", default-features = false, features = ["rustls-tls"] }
octocrab = { version = "0", default-features = false, features = ["rustls"] }
clap = { version = "3", features = ["derive"] }
serde_json = "1"
ansi_term = "0"
dialoguer = "0"
thiserror = "1"
ferinth = "2"
libium = "1"
online = "3"
semver = "1"
furse = "1"
url = "2"
