[package]
name = "ferium"
version = "3.4.0"
edition = "2021"
authors = ["theRookieCoder"]
description = "Ferium is an easy to use manager for Minecraft mods on Modrinth and Github Releases"
repository = "https://github.com/theRookieCoder/ferium"
license = "GNU LGPL 2.1"
readme = "README.md"
publish = false

[dependencies]
tokio = { version = "1.11", features = ["full"] }
reqwest = { version = "*", features = ["json"] }
serde = { version = "*", features = ["derive"] }
clap = {version = "*", features = ["yaml"]}
native-dialog = "*"
fancy-regex = "*"
shellexpand = "*"
serde_json = "*"
dialoguer = "*"
online = "*"
bytes = "*"
