[package]
name = "ferium"
version = "3.0.0"
edition = "2018"
authors = ["theRookieCoder"]

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bytes = "1"
shellexpand = "2"
