[package]
name = "ferium"
version = "3.10.0"
edition = "2021"
authors = ["theRookieCoder <ileshkt@gmail.com>"]
description = "Ferium is an easy to use CLI program for managing Minecraft mods on Modrinth and Github Releases"
repository = "https://github.com/theRookieCoder/ferium"
readme = "README.md"
license = "MPL-2.0"
publish = false

[dependencies]
# Use `rustls` rather than OpenSSL
reqwest = { version = "0", default-features = false, features = ["rustls-tls"] }
octocrab = { version = "0", default-features = false, features = ["rustls"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
clap = { version = "3", features = ["derive"] }
shellexpand = "2"
serde_json = "1"
ansi_term = "0"
dialoguer = "0"
thiserror = "1"
ferinth = "1"
online = "3"
bytes = "1"
onig = "6"
rfd = "0"
