[package]
name = "ferium"
version = "3.26.0"
edition = "2021"
authors = ["Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>", "Daniel Hauck (SolidTux)"]
description = "Ferium is a CLI program for managing Minecraft mods from Modrinth, CurseForge, and Github Releases"
exclude = ["tests"] # Don't need tests for installing using crates.io
repository = "https://github.com/theRookieCoder/ferium"
categories = ["command-line-utilities"]
readme = "README.md"
license = "MPL-2.0"
keywords = [
    "minecraft",
    "mod-manager",
    "modrinth",
    "curseforge",
    "github"
]

[features]
default = ["gui"]
gui = ["libium/gui"]

[dependencies]
tokio = { version = "1.18", default-features = false, features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
octocrab = { version = "0.16", default-features = false, features = ["rustls"] }
clap = { version = "3.1", features = ["derive"] }
lazy_static = "1.4"
dialoguer = "0.10"
serde_json = "1.0"
itertools = "0.10"
fs_extra = "1.2"
colored = "2.0"
ferinth = "2.2"
libium = "1.11"
anyhow = "1.0"
online = "3.0"
semver = "1.0"
bytes = "1.1"
furse = "1.1"
url = "2.2"

[dev-dependencies]
rand = "0.8"
