[package]
name = "ferium"
version = "3.2.0"
edition = "2018"
authors = ["theRookieCoder"]

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1.11", features = ["full"] }
serde = { version = "1", features = ["derive"] }
clap = {version = "2", features = ["yaml"]}
shellexpand = "2"
serde_json = "1"
bytes = "1"
