[package]
name = "ferium"
version = "3.6.0"
edition = "2021"
authors = ["theRookieCoder <ileshkt@gmail.com>"]
description = "Ferium is an easy to use manager for Minecraft mods on Modrinth and Github Releases"
repository = "https://github.com/theRookieCoder/ferium"
readme = "README.md"
license = "MPL-2.0"
publish = false

[dependencies]
tokio = { version = "*", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "*", features = ["json"] }
serde = { version = "*", features = ["derive"] }
clap = {version = "*", features = ["yaml"]}
fancy-regex = "*"
shellexpand = "*"
serde_json = "*"
dialoguer = "*"
online = "*"
bytes = "*"
rfd = "*"
